<a href="https://colab.research.google.com/github/Sahab00/uni_work_collab/blob/main/Neural_Network_initial_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Excercise
The torch package has been imported,
.
.
.
4.Add the resulting tensors, tensor_c and tensor_d, from the two previous steps together and assign it to tensor_e.

In [ ]:
import numpy as np
import torch

# Create two arrays
array_a = np.array([[1, 2, 3], [4, 5, 6]])
array_b = np.array([[6, 5, 4], [3, 2, 1]])

# Create two tensors from the arrays
tensor_a = torch.from_numpy(array_a)
tensor_b = torch.from_numpy(array_b)

# Subtract tensor_b from tensor_a
tensor_c = tensor_a - tensor_b

# Multiply each element of tensor_a with each element of tensor_b (element-wise multiplication)
tensor_d = tensor_a * tensor_b

# Add tensor_c to tensor_d
tensor_e = tensor_c + tensor_d

print(tensor_e)


tensor([[ 1,  7, 11],
        [13, 13, 11]], dtype=torch.int32)


Excercise
Your first neural network

In this exercise,
.
.
.
Use any output dimension for the first layer you want.

In [ ]:
import torch
import torch.nn as nn

input_tensor = torch.Tensor([[2, 3, 6, 7, 9, 3, 2, 1]])

# Implement a small neural network with exactly two linear layers
model = nn.Sequential(
    nn.Linear(8, 4),  # First layer takes 8 inputs and outputs 4
    nn.ReLU(),        # Activation functionS
    nn.Linear(4, 1)   # Second layer takes 4 inputs and outputs 1
)

output = model(input_tensor)
print(output)


tensor([[-1.6591]], grad_fn=<AddmmBackward0>)


In [ ]:
import torch
import torch.nn as nn

# Input tensor (1x12)
input_tensor = torch.Tensor([[2, 3, 6, 7, 9, 3, 2, 1, 5, 3, 6, 9]])

# Define the neural network with three hidden layers and an output of size 2
model = nn.Sequential(
    nn.Linear(12, 20), # First layer
    nn.Linear(20, 14), # Second layer
    nn.Linear(14, 3),  # Third layer
    nn.Linear(3, 2)    # Output layer
)

output = model(input_tensor)
print(output)


tensor([[ 0.9197, -0.4636]], grad_fn=<AddmmBackward0>)


In [ ]:
import torch

input_tensor = torch.tensor([[0.8]])

# Create a sigmoid function and apply it on input_tensor
sigmoid = torch.sigmoid(input_tensor)
probability_sigmoid = sigmoid
print("Sigmoid Probability:", probability_sigmoid)

# Create a softmax function and apply it on input_tensor
softmax = torch.softmax(input_tensor, dim=1)
probability_softmax = softmax
print("Softmax Probability:", probability_softmax)


Sigmoid Probability: tensor([[0.6900]])
Softmax Probability: tensor([[1.]])


In [ ]:
import torch

input_tensor = torch.tensor([[0.8]])

# Create a sigmoid function and apply it on input_tensor
sigmoid = torch.sigmoid(input_tensor)
probability_sigmoid = sigmoid
print("Sigmoid Probability:", probability_sigmoid)

# Create a softmax function and apply it on input_tensor
softmax = torch.softmax(input_tensor, dim=1)
probability_softmax = softmax
print("Softmax Probability:", probability_softmax)


Sigmoid Probability: tensor([[0.6900]])
Softmax Probability: tensor([[1.]])


In [ ]:
import torch
import torch.nn as nn

input_tensor = torch.Tensor([[3, 4, 6, 2, 3, 6, 8, 9]])

# Implement a small neural network for binary classification
model = nn.Sequential(
    nn.Linear(8, 1),  # One input (8 features) to one output
    nn.Sigmoid()      # Sigmoid activation for binary classification
)

output = model(input_tensor)
print(output)


tensor([[0.9817]], grad_fn=<SigmoidBackward0>)


In [ ]:
import torch
import torch.nn as nn

input_tensor = torch.Tensor([[3, 4, 6, 7, 10, 12, 2, 3, 6, 8, 9]])

# Implement a neural network with exactly four linear layers for regression
model = nn.Sequential(
    nn.Linear(11, 20), # Example sizes for hidden layers
    nn.Linear(20, 15),
    nn.Linear(15, 10),
    nn.Linear(10, 1)   # Output layer for regression
)

output = model(input_tensor)
print(output)


tensor([[-0.5510]], grad_fn=<AddmmBackward0>)


In [ ]:
import torch
import torch.nn as nn

input_tensor = torch.Tensor([[3, 4, 6, 7, 10, 12, 2, 3, 6, 8, 9]])

# Update network to perform a multi-class classification with four labels
model = nn.Sequential(
    nn.Linear(11, 20), # Example sizes for hidden layers
    nn.Linear(20, 15),
    nn.Linear(15, 10),
    nn.Linear(10, 4)   # Output layer with 4 outputs for multi-class
)

output = model(input_tensor)
print(output)


tensor([[-1.0606, -0.4228, -0.7738, -1.5641]], grad_fn=<AddmmBackward0>)


In [ ]:
#Exercise 4: True Statements about Neural Networks

True: A neural network with a single linear layer followed by a sigmoid activation is similar to a logistic regression model.
False: A neural network can only contain two linear layers.
False: The softmax function takes a tensor of dimension N as input and outputs a float between zero and one. (It outputs a tensor where each element is between 0 and 1 and sums to 1.)
True: The input dimension of a linear layer must be equal to the output dimension of the previous layer.